// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager_message.proto

package org.bupt.fedraft.rpc.manager.message;

/**
 * Protobuf enum {@code fedraft.ManagerStatus}
 */
public enum ManagerStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LEADER = 0;</code>
   */
  LEADER(0),
  /**
   * <code>CANDIDATE = 1;</code>
   */
  CANDIDATE(1),
  /**
   * <code>FOLLOWER = 2;</code>
   */
  FOLLOWER(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LEADER = 0;</code>
   */
  public static final int LEADER_VALUE = 0;
  /**
   * <code>CANDIDATE = 1;</code>
   */
  public static final int CANDIDATE_VALUE = 1;
  /**
   * <code>FOLLOWER = 2;</code>
   */
  public static final int FOLLOWER_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ManagerStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ManagerStatus forNumber(int value) {
    switch (value) {
      case 0: return LEADER;
      case 1: return CANDIDATE;
      case 2: return FOLLOWER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ManagerStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ManagerStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ManagerStatus>() {
          public ManagerStatus findValueByNumber(int number) {
            return ManagerStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.bupt.fedraft.rpc.manager.message.ManagerMessage.getDescriptor().getEnumTypes().get(0);
  }

  private static final ManagerStatus[] VALUES = values();

  public static ManagerStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  ManagerStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fedraft.ManagerStatus)
}

