// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobmanager_message.proto

package org.bupt.fedraft.rpc.jobmanager.message;

public interface AppendModelsResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fedraft.AppendModelsResponse)
        com.google.protobuf.MessageOrBuilder {
}
