// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobmanager_message.proto

package org.bupt.fedraft.rpc.jobmanager.message;

public interface JobPullModelRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fedraft.JobPullModelRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 term = 1;</code>
     *
     * @return The term.
     */
    int getTerm();

    /**
     * <code>int64 modelIndex = 2;</code>
     *
     * @return The modelIndex.
     */
    long getModelIndex();
}
