// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobmanager_message.proto

package org.bupt.fedraft.rpc.jobmanager.message;

public interface JobPullModelResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fedraft.JobPullModelResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes modelChunk = 1;</code>
     *
     * @return The modelChunk.
     */
    com.google.protobuf.ByteString getModelChunk();
}
