// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_message.proto

package org.bupt.cad.fedraft.rpc.message;

public interface HeartbeatResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fedraft.HeartbeatResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 network_delay = 1;</code>
     *
     * @return The networkDelay.
     */
    int getNetworkDelay();

    /**
     * <code>.fedraft.NodeState node_state = 2;</code>
     *
     * @return The enum numeric value on the wire for nodeState.
     */
    int getNodeStateValue();

    /**
     * <code>.fedraft.NodeState node_state = 2;</code>
     *
     * @return The nodeState.
     */
    org.bupt.cad.fedraft.rpc.message.NodeState getNodeState();
}
