// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat_message.proto

package org.bupt.cad.fedraft.rpc.message;

public final class HeartbeatMessage {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_HeartbeatResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_HeartbeatResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_HeartbeatRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_HeartbeatRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_TrainerHeartbeatRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_TrainerHeartbeatRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_TrainerHeartbeatResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_TrainerHeartbeatResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\027heartbeat_message.proto\022\007fedraft\"R\n\021He" +
                        "artbeatResponse\022\025\n\rnetwork_delay\030\001 \001(\r\022&" +
                        "\n\nnode_state\030\002 \001(\0162\022.fedraft.NodeState\"\252" +
                        "\001\n\020HeartbeatRequest\022\014\n\004term\030\001 \001(\r\022\021\n\tlea" +
                        "der_id\030\002 \001(\004\022\027\n\017pre_model_index\030\003 \001(\r\022\026\n" +
                        "\016pre_model_term\030\004 \001(\r\022\032\n\022leader_model_in" +
                        "dex\030\005 \001(\r\022\020\n\010node_ids\030\006 \003(\004\022\026\n\016network_d" +
                        "elays\030\007 \003(\r\"\302\001\n\027TrainerHeartbeatRequest\022" +
                        "\014\n\004term\030\001 \001(\r\022\021\n\tleader_id\030\002 \001(\004\022\027\n\017pre_" +
                        "model_index\030\003 \001(\r\022\026\n\016pre_model_term\030\004 \001(" +
                        "\r\022\033\n\023current_model_index\030\005 \001(\r\022&\n\nnode_s" +
                        "tate\030\006 \001(\0162\022.fedraft.NodeState\022\020\n\010node_i" +
                        "ds\030\007 \003(\004\"7\n\030TrainerHeartbeatResponse\022\033\n\023" +
                        "current_model_index\030\001 \001(\r*S\n\tNodeState\022\r" +
                        "\n\tSAFE_MODE\020\000\022\016\n\nTMP_LEADER\020\001\022\n\n\006LEADER\020" +
                        "\002\022\r\n\tCANDIDATE\020\003\022\014\n\010FOLLOWER\020\004B$\n org.bu" +
                        "pt.cad.fedraft.rpc.messageP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_fedraft_HeartbeatResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_fedraft_HeartbeatResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_HeartbeatResponse_descriptor,
                new java.lang.String[]{"NetworkDelay", "NodeState",});
        internal_static_fedraft_HeartbeatRequest_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_fedraft_HeartbeatRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_HeartbeatRequest_descriptor,
                new java.lang.String[]{"Term", "LeaderId", "PreModelIndex", "PreModelTerm", "LeaderModelIndex", "NodeIds", "NetworkDelays",});
        internal_static_fedraft_TrainerHeartbeatRequest_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_fedraft_TrainerHeartbeatRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_TrainerHeartbeatRequest_descriptor,
                new java.lang.String[]{"Term", "LeaderId", "PreModelIndex", "PreModelTerm", "CurrentModelIndex", "NodeState", "NodeIds",});
        internal_static_fedraft_TrainerHeartbeatResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_fedraft_TrainerHeartbeatResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_TrainerHeartbeatResponse_descriptor,
                new java.lang.String[]{"CurrentModelIndex",});
    }

    private HeartbeatMessage() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
