// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_message.proto

package org.bupt.cad.fedraft.rpc.message;

public final class LogMessage {
    private LogMessage() {
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_LogRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_LogRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_LogResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_LogResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_LogPullRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_LogPullRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_LogPullResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_LogPullResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021log_message.proto\022\007fedraft\"{\n\nLogReque" +
                        "st\022\014\n\004term\030\001 \001(\r\022\021\n\tleader_id\030\002 \001(\004\022\023\n\013m" +
                        "odel_index\030\003 \001(\r\022\"\n\010log_type\030\004 \001(\0162\020.fed" +
                        "raft.LogType\022\023\n\013model_chunk\030\005 \001(\014\"4\n\013Log" +
                        "Response\022\023\n\013local_index\030\001 \001(\r\022\020\n\010log_siz" +
                        "e\030\002 \001(\004\"U\n\016LogPullRequest\022\014\n\004term\030\001 \001(\r\022" +
                        "\021\n\tleader_id\030\002 \001(\004\022\"\n\010log_type\030\003 \001(\0162\020.f" +
                        "edraft.LogType\";\n\017LogPullResponse\022\023\n\013mod" +
                        "el_chunk\030\001 \001(\014\022\023\n\013model_index\030\002 \001(\r*K\n\007L" +
                        "ogType\022\024\n\020CLIENT_TO_LEADER\020\000\022\024\n\020LEADER_T" +
                        "O_CLIENT\020\001\022\024\n\020CLIENT_TO_CLIENT\020\002B$\n org." +
                        "bupt.cad.fedraft.rpc.messageP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_fedraft_LogRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_fedraft_LogRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_LogRequest_descriptor,
                new java.lang.String[]{"Term", "LeaderId", "ModelIndex", "LogType", "ModelChunk",});
        internal_static_fedraft_LogResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_fedraft_LogResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_LogResponse_descriptor,
                new java.lang.String[]{"LocalIndex", "LogSize",});
        internal_static_fedraft_LogPullRequest_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_fedraft_LogPullRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_LogPullRequest_descriptor,
                new java.lang.String[]{"Term", "LeaderId", "LogType",});
        internal_static_fedraft_LogPullResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_fedraft_LogPullResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_LogPullResponse_descriptor,
                new java.lang.String[]{"ModelChunk", "ModelIndex",});
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
