// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_message.proto

package org.bupt.cad.fedraft.rpc.message;

public final class LogMessage {
  private LogMessage() {
  }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_LogRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_LogRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_LogResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_LogResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_HeartbeatResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_HeartbeatResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_fedraft_HeartbeatRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_fedraft_HeartbeatRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021log_message.proto\022\007fedraft\"\331\001\n\nLogRequ" +
                        "est\022\014\n\004term\030\001 \001(\r\022\021\n\tleader_id\030\002 \001(\004\022\027\n\017" +
                        "pre_model_index\030\003 \001(\r\022\026\n\016pre_model_term\030" +
                        "\004 \001(\r\022-\n\010log_type\030\005 \001(\0162\033.fedraft.LogReq" +
                        "uest.LogType\022\023\n\013model_chunk\030\006 \001(\014\"5\n\007Log" +
                        "Type\022\024\n\020CLIENT_TO_LEADER\020\000\022\024\n\020LEADER_TO_" +
                        "CLIENT\020\001\"4\n\013LogResponse\022\023\n\013local_index\030\001" +
                        " \001(\r\022\020\n\010log_size\030\002 \001(\004\"*\n\021HeartbeatRespo" +
                        "nse\022\025\n\rnetwork_delay\030\001 \001(\002\"]\n\020HeartbeatR" +
                        "equest\022\014\n\004term\030\001 \001(\r\022\021\n\tleader_id\030\002 \001(\004\022" +
                        "\020\n\010node_ids\030\003 \003(\004\022\026\n\016network_delays\030\004 \003(" +
                        "\002B$\n org.bupt.cad.fedraft.rpc.messageP\001b" +
                        "\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_fedraft_LogRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_fedraft_LogRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_LogRequest_descriptor,
                new java.lang.String[]{"Term", "LeaderId", "PreModelIndex", "PreModelTerm", "LogType", "ModelChunk",});
        internal_static_fedraft_LogResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_fedraft_LogResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_LogResponse_descriptor,
                new java.lang.String[]{"LocalIndex", "LogSize",});
        internal_static_fedraft_HeartbeatResponse_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_fedraft_HeartbeatResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_HeartbeatResponse_descriptor,
                new java.lang.String[]{"NetworkDelay",});
        internal_static_fedraft_HeartbeatRequest_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_fedraft_HeartbeatRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_fedraft_HeartbeatRequest_descriptor,
                new java.lang.String[]{"Term", "LeaderId", "NodeIds", "NetworkDelays",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
