// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat_message.proto

package org.bupt.cad.fedraft.rpc.message;

/**
 * Protobuf type {@code fedraft.SyncWithTrainerResponse}
 */
public final class SyncWithTrainerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fedraft.SyncWithTrainerResponse)
    SyncWithTrainerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SyncWithTrainerResponse.newBuilder() to construct.
  private SyncWithTrainerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncWithTrainerResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SyncWithTrainerResponse();
  }

  @java.lang.Override
  public com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final int CURRENT_MODEL_INDEX_FIELD_NUMBER = 1;

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.bupt.cad.fedraft.rpc.message.HeartbeatMessage.internal_static_fedraft_SyncWithTrainerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.class, org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.Builder.class);
  }
  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  // @@protoc_insertion_point(class_scope:fedraft.SyncWithTrainerResponse)
  private static final org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse DEFAULT_INSTANCE;
  /**
   * <code>uint32 current_model_index = 1;</code>
   * @return The currentModelIndex.
   */
  @java.lang.Override
  public int getCurrentModelIndex() {
    return currentModelIndex_;
  }
  private static final com.google.protobuf.Parser<SyncWithTrainerResponse>
      PARSER = new com.google.protobuf.AbstractParser<SyncWithTrainerResponse>() {
    @java.lang.Override
    public SyncWithTrainerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  static {
    DEFAULT_INSTANCE = new org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse();
  }
  /**
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private int currentModelIndex_;
  @java.lang.Override
  public boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentModelIndex_ != 0) {
      output.writeUInt32(1, currentModelIndex_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(2, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentModelIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, currentModelIndex_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }
  private long timestamp_;

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_MODEL_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentModelIndex();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  private byte memoizedIsInitialized = -1;
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.bupt.cad.fedraft.rpc.message.HeartbeatMessage.internal_static_fedraft_SyncWithTrainerResponse_descriptor;
  }

  public static org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<SyncWithTrainerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse)) {
      return super.equals(obj);
    }
    org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse other = (org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse) obj;

    if (getCurrentModelIndex()
        != other.getCurrentModelIndex()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
      return getUnknownFields().equals(other.getUnknownFields());
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncWithTrainerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code fedraft.SyncWithTrainerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fedraft.SyncWithTrainerResponse)
      org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponseOrBuilder {
    public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bupt.cad.fedraft.rpc.message.HeartbeatMessage.internal_static_fedraft_SyncWithTrainerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bupt.cad.fedraft.rpc.message.HeartbeatMessage.internal_static_fedraft_SyncWithTrainerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.class, org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.Builder.class);
    }

    private int currentModelIndex_ ;
    private long timestamp_ ;
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentModelIndex_ = 0;

      timestamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.bupt.cad.fedraft.rpc.message.HeartbeatMessage.internal_static_fedraft_SyncWithTrainerResponse_descriptor;
    }

    @java.lang.Override
    public org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse getDefaultInstanceForType() {
      return org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse build() {
      org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse buildPartial() {
      org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse result = new org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse(this);
      result.currentModelIndex_ = currentModelIndex_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse) {
        return mergeFrom((org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse other) {
      if (other == org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.getDefaultInstance()) return this;
      if (other.getCurrentModelIndex() != 0) {
        setCurrentModelIndex(other.getCurrentModelIndex());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              currentModelIndex_ = input.readUInt32();

              break;
            } // case 8
            case 16: {
              timestamp_ = input.readUInt64();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // Construct using org.bupt.cad.fedraft.rpc.message.SyncWithTrainerResponse.newBuilder()
    private Builder() {

    }
    /**
     * <code>uint32 current_model_index = 1;</code>
     * @return The currentModelIndex.
     */
    @java.lang.Override
    public int getCurrentModelIndex() {
      return currentModelIndex_;
    }
    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }

    /**
     * <code>uint32 current_model_index = 1;</code>
     * @param value The currentModelIndex to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentModelIndex(int value) {

      currentModelIndex_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>uint32 current_model_index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentModelIndex() {

      currentModelIndex_ = 0;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {

      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fedraft.SyncWithTrainerResponse)
  }

}

