// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat_message.proto

package org.bupt.cad.fedraft.rpc.message;

public interface TrainerHeartbeatResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fedraft.TrainerHeartbeatResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 current_model_index = 1;</code>
     *
     * @return The currentModelIndex.
     */
    int getCurrentModelIndex();
}
